Repository src-d/metadata-retrieval, pull requests merged in 2019-10, with the labels that each got.

#29 Add more downloader tests by recording and replaying
  .travis.yml
  README.md
  examples/cmd/testing/recordingscript.go
  github/downloader_test.go
  go.mod
  go.sum
  testdata/offline-organization-tests.json
  testdata/offline-repository-tests.json
  testdata/organization_src-d_2019-10-14.gob.gz
  testdata/repository_src-d_gitbase_2019-10-14.gob.gz
  testutils/memory.go
  testutils/teststructs.go
Labels: enhancement

#58 Enhance docs
  README.md
Labels: bug, documentation

#57 Handle RateLimit and Abuse errors
  examples/cmd/main.go
  github/downloader.go
  github/httpbody.go
  github/ratelimit.go
  github/ratelimit_test.go
  github/retry.go
  testutils/logger.go
Labels: bug, enhancement

#20 Add footer to README, with License, CoC and Contrib
  .github/CODE_OF_CONDUCT.md
  DCO
  LICENSE.md
  NOTICE.md
  README.md
Labels: documentation, enhancement

#71 Make RateLimitTransport to log Abuse or RateLimit as Info
  github/ratelimit.go
  github/ratelimit_test.go
Labels: enhancement
